name: Deploy Lambda Function

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust the Node.js version as needed

      - name: Install ncc Locally
        run: npm install @vercel/ncc

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: npm install
        env:
          CI: true
        run: npm install

      - name: Build and Deploy
        run: |
          npm run build 
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=test123 --zip-file=fileb://deploy.zip
